services:
  frontend:
  #    depends_on:
  #      backend:
  #        condition: service_healthy
  #        restart: true
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dotcer/praciya-frontend:latest
    ports:
      - 4200:4200
    networks:
      - myNetwork
  #    working_dir: /app
  #    volumes:
  #      - ./frontend:/app

  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dotcer/praciya-backend:latest
    ports:
      - 3000:3000
    networks:
      - myNetwork
#    working_dir: /app
#    volumes:
#      - ./backend:/app
#    healthcheck:



networks:
  myNetwork:
    driver: bridge